# Generated by Django 4.2.6 on 2023-11-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0002_alter_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='icon',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='ways_to_find',
            field=models.CharField(max_length=100),
        ),
    ]
