# Generated by Django 4.2.6 on 2023-11-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0003_socialmedia_alter_contactus_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='has_button',
            field=models.BooleanField(default=False),
        ),
    ]
