# Generated by Django 4.2.6 on 2023-11-06 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0006_company_alter_pages_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
